### ISSUE TITLE
Must如果第二个参数可以省略就更好了

### ISSUE THREAD

**Issue by dulumao** [issue9/conv#1]
RT

**Comment by caixw** [comment]
这是历史遗留问题，如果要改的话，可能要等下个大版本了。

**Comment by dulumao** [comment]
啥时候更新下一个版本呀

**Comment by caixw** [comment]
你如果有空的话，可以直接提交一个 PR 过来。去掉默认参数，出错直接 panic 就可以了。

Matt Ma <notifications@github.com> 于2020年5月16日周六 下午4:23写道：

**Comment by dulumao** [comment]
ok
